import { PaymentMethod } from "../../types";

export const MIDTRANS_STATIC_METHODS: PaymentMethod[] = [
  {
    paymentMethod: "credit_card",
    code: "credit_card",
    paymentName: "Credit / Debit Card (Visa, Mastercard, JCB)",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/credit_card.png",
    totalFee: "2.9% + IDR 2,000",
    category: "Kartu Kredit",
    feeDetail: { flat: 2000, percent: 2.9, totalFee: 2000 },
  },
  {
    paymentMethod: "bca_va",
    code: "bca_va",
    paymentName: "BCA Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/bca_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "mandiri_va",
    code: "mandiri_va",
    paymentName: "Mandiri Bill Payment / VA",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/mandiri_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "bni_va",
    code: "bni_va",
    paymentName: "BNI Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/bni_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "bri_va",
    code: "bri_va",
    paymentName: "BRI Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/bri_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "permata_va",
    code: "permata_va",
    paymentName: "Permata Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/permata_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "cimb_va",
    code: "cimb_va",
    paymentName: "CIMB Niaga Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/cimb_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "bsi_va",
    code: "bsi_va",
    paymentName: "BSI Virtual Account",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/bsi_va.png",
    totalFee: "IDR 4,000",
    category: "Virtual Account",
    feeDetail: { flat: 4000, percent: 0, totalFee: 4000 },
  },
  {
    paymentMethod: "qris",
    code: "qris",
    paymentName: "QRIS Universal (GoPay, ShopeePay, DANA, OVO, LinkAja, BCA Mobile)",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/qris.png",
    totalFee: "0.7%",
    category: "QRIS",
    feeDetail: { flat: 0, percent: 0.7, totalFee: 0 },
  },
  {
    paymentMethod: "gopay",
    code: "gopay",
    paymentName: "GoPay E-Wallet & QRIS",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/gopay.png",
    totalFee: "2.0%",
    category: "E-Wallet",
    feeDetail: { flat: 0, percent: 2.0, totalFee: 0 },
  },
  {
    paymentMethod: "shopeepay",
    code: "shopeepay",
    paymentName: "ShopeePay E-Wallet & QRIS",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/shopeepay.png",
    totalFee: "2.0%",
    category: "E-Wallet",
    feeDetail: { flat: 0, percent: 2.0, totalFee: 0 },
  },
  {
    paymentMethod: "ovo",
    code: "ovo",
    paymentName: "OVO E-Wallet",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/ovo.png",
    totalFee: "1.5%",
    category: "E-Wallet",
    feeDetail: { flat: 0, percent: 1.5, totalFee: 0 },
  },
  {
    paymentMethod: "dana",
    code: "dana",
    paymentName: "DANA E-Wallet",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/dana.png",
    totalFee: "1.7%",
    category: "E-Wallet",
    feeDetail: { flat: 0, percent: 1.7, totalFee: 0 },
  },
  {
    paymentMethod: "linkaja",
    code: "linkaja",
    paymentName: "LinkAja E-Wallet",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/linkaja.png",
    totalFee: "1.7%",
    category: "E-Wallet",
    feeDetail: { flat: 0, percent: 1.7, totalFee: 0 },
  },
  {
    paymentMethod: "indomaret",
    code: "indomaret",
    paymentName: "Indomaret",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/indomaret.png",
    totalFee: "IDR 5,000",
    category: "Retail / Gerai",
    feeDetail: { flat: 5000, percent: 0, totalFee: 5000 },
  },
  {
    paymentMethod: "alfamart",
    code: "alfamart",
    paymentName: "Alfamart / Alfamidi",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/alfamart.png",
    totalFee: "IDR 5,000",
    category: "Retail / Gerai",
    feeDetail: { flat: 5000, percent: 0, totalFee: 5000 },
  },
  {
    paymentMethod: "kredivo",
    code: "kredivo",
    paymentName: "Kredivo Paylater",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/kredivo.png",
    totalFee: "2.3%",
    category: "Paylater / Cicilan",
    feeDetail: { flat: 0, percent: 2.3, totalFee: 0 },
  },
  {
    paymentMethod: "akulaku",
    code: "akulaku",
    paymentName: "Akulaku Paylater",
    paymentImage: "https://docs.midtrans.com/asset/payment_methods/akulaku.png",
    totalFee: "1.7%",
    category: "Paylater / Cicilan",
    feeDetail: { flat: 0, percent: 1.7, totalFee: 0 },
  },
];

export const MIDTRANS_PROBE_PAYLOADS: Record<string, any> = {
  qris: { payment_type: "qris", qris: { acquirer: "gopay" } },
  gopay: { payment_type: "gopay", gopay: { enable_callback: true, callback_url: "https://example.com" } },
  shopeepay: { payment_type: "shopeepay", shopeepay: { callback_url: "https://example.com" } },
  ovo: { payment_type: "ovo", ovo: { phone: "081234567890" } },
  dana: { payment_type: "dana" },
  linkaja: { payment_type: "linkaja" },
  bca: { payment_type: "bank_transfer", bank_transfer: { bank: "bca" } },
  bni: { payment_type: "bank_transfer", bank_transfer: { bank: "bni" } },
  bri: { payment_type: "bank_transfer", bank_transfer: { bank: "bri" } },
  cimb: { payment_type: "bank_transfer", bank_transfer: { bank: "cimb" } },
  danamon: { payment_type: "bank_transfer", bank_transfer: { bank: "danamon" } },
  bsi: { payment_type: "bank_transfer", bank_transfer: { bank: "bsi" } },
  seabank: { payment_type: "bank_transfer", bank_transfer: { bank: "seabank" } },
  mandiri: { payment_type: "echannel", echannel: { bill_info1: "Payment", bill_info2: "Probe" } },
  permata: { payment_type: "permata" },
  alfamart: { payment_type: "cstore", cstore: { store: "alfamart", message: "Probe" } },
  indomaret: { payment_type: "cstore", cstore: { store: "indomaret", message: "Probe" } },
  akulaku: { payment_type: "akulaku" },
  kredivo: {
    payment_type: "kredivo",
    seller_details: { address: { city: "Jakarta" } },
  },
};
